CREATE TABLE Account (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  picture VARCHAR(255)
);

CREATE TABLE Recipe (
  id INT PRIMARY KEY AUTO_INCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  instructions VARCHAR(5000),
  img VARCHAR(1000),
  category ENUM('Breakfast','Lunch','Dinner','Snack','Dessert') NOT NULL,
  creator_id VARCHAR(255),
  FOREIGN KEY (creator_id) REFERENCES Account(id)
);

CREATE TABLE Ingredient (
  id INT PRIMARY KEY AUTO_INCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(255) NOT NULL,
  quantity VARCHAR(255),
  FOREIGN KEY (recipe_id) REFERENCES Recipe(id)
);

CREATE TABLE Favorite (
  id INT PRIMARY KEY AUTO_INCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  recipe_id INT,
  account_id VARCHAR(255),
  FOREIGN KEY (recipe_id) REFERENCES Recipe(id),
  FOREIGN KEY (account_id) REFERENCES Account(id)
);